### ISSUE TITLE
'toggled' menu items go off the bottom of the page.

### ISSUE THREAD

**Issue by bobg2015** [pramod-rathod-avalara/startbootstrap-sb-admin-2-sidebar-toggle#4]
Hi,

If you have a large amount of items in a list the list will go off the bottom of the browser page and not be visible/accessible. This appears to be because the menu elements just overlay ( not sure if thats the correct term) over the existing page and the scrolling is therefore restricted to the existing pages height.

Is there a way to build an internal scrolling mechanism into the nav menus when collapsed?

**Comment by pramod-rathod-avalara** [comment]
Hi,

Please check if the below resolves your issue.

``` css
.scrollable {
  overflow-y: scroll;
  height: 100vh;
  margin-bottom: -101px;
}
```

``` html
<div id="sidebar-wrapper">
                <div class="navbar-default sidebar scrollable" role="navigation">
                  ....
               </div>
</div>
```

**Comment by bobg2015** [comment]
Thank you. That kind of works but I needed to add the scrollable class to the unordered list not in the sidebar. i.e

```
<ul class="nav nav-fourth-level scrollable collapse">
```

Is there a way to have the height and margin resize to fit the amount of list items better?

**Comment by pramod-rathod-avalara** [comment]
Hi,

Not sure if the below is what you need, but you can work with the below CSS. For the sub-menu I have kept the size 400px max, so it can accommodate 10 menu items. If you are looking for something that auto fits within the view-port then you may need to do it using JavaScript by setting the bottom:0, check these links may be helpful [http://jsfiddle.net/G7qfq/5/](http://jsfiddle.net/G7qfq/5/) and [https://github.com/twbs/bootstrap/pull/12328](https://github.com/twbs/bootstrap/pull/12328)

``` css
.scrollable-menu {
  overflow-y: scroll;
  height: 100vh;
  margin-bottom: -101px;
}

.scrollable-sub-menu {
    max-height: 400px;
    overflow: hidden;
    overflow-y: auto;
}
```
